### ISSUE TITLE
File System or Blob?

### ISSUE THREAD

**Issue by GeoffreyEmery** [Azure/azurefile-dockervolumedriver#33]
Hello,
  Thanks for posting this. The links states file system is for one node where blob is for many. But your documentation sates it as file is one to two many. Can you clear up what the best solution is? 
     Do you have a docker image using blob storage as the /data. 
Cheers,
  Geoff

**Comment by ahmetb** [comment]
@GeoffreyEmery what are you specifically referring to? Azure Blob Storage Service is not related to this project.

**Comment by GeoffreyEmery** [comment]
@ahmetalpbalkan ,
   Good morning thanks for the fast reply on this. Based on this [diagram](https://acom.azurecomcdn.net/80C57D/cdn/mediahandler/docarticles/dpsmedia-prod/azure.microsoft.com/en-us/documentation/articles/storage-introduction/20160527062741/storage-concepts.png) from this [article](https://azure.microsoft.com/en-us/documentation/articles/storage-introduction/#introducing-the-azure-storage-services). I am trying to figure out the best practice. It appears as always it may be based on the use case and the type of underlying storage implementation it uses  Trying to put the pieces together here. Lets use this use case:
  **infrsatracture**:  Docker Cloud Container cluster on two A2 vm's. 
  **software**:  Let uses this container stack i have set up on azure right now minus the data volumes which the point of the thread.  

```
   data:
  image: 'busybox:latest'
  volumes:
    - /var/www/html/wp-content
    - /var/lib/mysql
mysql:
  environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_PASS=myPass
  image: 'tutum/mysql:latest'
  volumes_from:
    - data
web:
  environment:
    - WORDPRESS_DB_PASSWORD=myPass
  image: 'wordpress:latest'
  links:
    - mysql
  ports:
    - '80:80'
 volumes_from:
    - data
  working_dir: /var/www/html
```

My question relates to the data volumes. I am trying to figure out what is the best busy data storage model for both the mysql storage and the wp-content storage.  Since wp-content is mostly pictures that are write once read many it would lead me to blob storage and perhaps some read only mysql nodes. Since mysql write is high iops this would lead to file system? In reality they could both be used for either. What are you thoughts? Any best practice you can point me to? I really like this approach as it avoids me having to add things like this [word press plugin](https://wordpress.org/plugins/windows-azure-storage/)  Since its already running in azure.
