### ISSUE TITLE
Containers "chown"ing files in Azure File Storage

### ISSUE THREAD

**Issue by williamayerst** [Azure/azurefile-dockervolumedriver#65]
The Postgresql container (https://hub.docker.com/_/postgres/) runs a script on start which attempts to own its data folder, and this fails:

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/data ...
```

I am mounting the Azure file storage location to /var/lib/postgresql/data as below:

```
services:
  db:
    ...
    volumes:
      - postgresql:/var/lib/postgresql/data
    ...
volumes:
  postgresql:
    driver: azurefile
    driver_opts:
      share: "postgresql"

```

I have tried creating a remotepath "data" and it makes no difference. I take it this is because the storage driver can't interpret that call, is there a workaround?
